# This file was generated by GoReleaser. DO NOT EDIT.
class Awsets < Formula
  desc "A utility for crawling an AWS account and exporting all its resources for further analysis."
  homepage "https://github.com/trek10inc/awsets"
  version "0.2.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/trek10inc/awsets/releases/download/v0.2.7/awsets_0.2.7_darwin_x86_64.tar.gz"
    sha256 "d4049f92ad5bca6adfa83659f91f6133554baf3bc2ac09151c11c589120a6194"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/trek10inc/awsets/releases/download/v0.2.7/awsets_0.2.7_linux_x86_64.tar.gz"
      sha256 "92ca768874d0c17ad2c9a3e249d2dd14e8a610d204324366132f8177c77b1c5f"
    end
  end

  def install
    bin.install "awsets"
  end
end
